INSERT INTO country(country_name, iso_code) VALUES ('Afghanistan', 'AF') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Åland Islands', 'AX') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Albania', 'AL') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Algeria', 'DZ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('American Samoa', 'AS') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Andorra', 'AD') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Angola', 'AO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Anguilla', 'AI') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Antarctica', 'AQ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Antigua and Barbuda', 'AG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Argentina', 'AR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Armenia', 'AM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Aruba', 'AW') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Australia', 'AU') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Austria', 'AT') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Azerbaijan', 'AZ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Bahamas', 'BS') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Bahrain', 'BH') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Bangladesh', 'BD') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Barbados', 'BB') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Belarus', 'BY') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Belgium', 'BE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Belize', 'BZ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Benin', 'BJ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Bermuda', 'BM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Bhutan', 'BT') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Bolivia (Plurinational State of)', 'BO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Bonaire, Sint Eustatius and Saba', 'BQ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Bosnia and Herzegovina', 'BA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Botswana', 'BW') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Bouvet Island', 'BV') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Brazil', 'BR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('British Indian Ocean Territory', 'IO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Brunei Darussalam', 'BN') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Bulgaria', 'BG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Burkina Faso', 'BF') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Burundi', 'BI') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Cabo Verde', 'CV') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Cambodia', 'KH') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Cameroon', 'CM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Canada', 'CA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Cayman Islands', 'KY') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Central African Republic', 'CF') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Chad', 'TD') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Chile', 'CL') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('China', 'CN') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Christmas Island', 'CX') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Cocos (Keeling) Islands', 'CC') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Colombia', 'CO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Comoros', 'KM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Congo', 'CG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Congo (Democratic Republic of the)', 'CD') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Cook Islands', 'CK') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Costa Rica', 'CR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Côte d''Ivoire', 'CI') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Croatia', 'HR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Cuba', 'CU') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Curaçao', 'CW') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Cyprus', 'CY') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Czechia', 'CZ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Denmark', 'DK') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Djibouti', 'DJ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Dominica', 'DM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Dominican Republic', 'DO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Ecuador', 'EC') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Egypt', 'EG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('El Salvador', 'SV') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Equatorial Guinea', 'GQ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Eritrea', 'ER') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Estonia', 'EE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Eswatini', 'SZ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Ethiopia', 'ET') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Falkland Islands (Malvinas)', 'FK') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Faroe Islands', 'FO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Fiji', 'FJ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Finland', 'FI') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('France', 'FR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('French Guiana', 'GF') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('French Polynesia', 'PF') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('French Southern Territories', 'TF') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Gabon', 'GA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Gambia', 'GM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Georgia', 'GE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Germany', 'DE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Ghana', 'GH') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Gibraltar', 'GI') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Greece', 'GR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Greenland', 'GL') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Grenada', 'GD') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Guadeloupe', 'GP') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Guam', 'GU') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Guatemala', 'GT') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Guernsey', 'GG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Guinea', 'GN') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Guinea-Bissau', 'GW') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Guyana', 'GY') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Haiti', 'HT') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Heard Island and McDonald Islands', 'HM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Holy See', 'VA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Honduras', 'HN') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Hong Kong', 'HK') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Hungary', 'HU') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Iceland', 'IS') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('India', 'IN') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Indonesia', 'ID') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Iran (Islamic Republic of)', 'IR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Iraq', 'IQ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Ireland', 'IE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Isle of Man', 'IM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Israel', 'IL') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Italy', 'IT') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Jamaica', 'JM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Japan', 'JP') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Jersey', 'JE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Jordan', 'JO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Kazakhstan', 'KZ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Kenya', 'KE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Kiribati', 'KI') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Korea (Democratic People''s Republic of)', 'KP') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Korea (Republic of)', 'KR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Kuwait', 'KW') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Kyrgyzstan', 'KG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Lao People''s Democratic Republic', 'LA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Latvia', 'LV') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Lebanon', 'LB') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Lesotho', 'LS') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Liberia', 'LR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Libya', 'LY') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Liechtenstein', 'LI') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Lithuania', 'LT') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Luxembourg', 'LU') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Macao', 'MO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Macedonia (the former Yugoslav Republic of)', 'MK') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Madagascar', 'MG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Malawi', 'MW') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Malaysia', 'MY') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Maldives', 'MV') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Mali', 'ML') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Malta', 'MT') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Marshall Islands', 'MH') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Martinique', 'MQ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Mauritania', 'MR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Mauritius', 'MU') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Mayotte', 'YT') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Mexico', 'MX') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Micronesia (Federated States of)', 'FM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Moldova (Republic of)', 'MD') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Monaco', 'MC') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Mongolia', 'MN') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Montenegro', 'ME') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Montserrat', 'MS') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Morocco', 'MA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Mozambique', 'MZ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Myanmar', 'MM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Namibia', 'NA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Nauru', 'NR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Nepal', 'NP') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Netherlands', 'NL') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('New Caledonia', 'NC') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('New Zealand', 'NZ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Nicaragua', 'NI') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Niger', 'NE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Nigeria', 'NG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Niue', 'NU') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Norfolk Island', 'NF') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Northern Mariana Islands', 'MP') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Norway', 'NO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Oman', 'OM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Pakistan', 'PK') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Palau', 'PW') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Palestine, State of', 'PS') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Panama', 'PA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Papua New Guinea', 'PG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Paraguay', 'PY') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Peru', 'PE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Philippines', 'PH') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Pitcairn', 'PN') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Poland', 'PL') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Portugal', 'PT') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Puerto Rico', 'PR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Qatar', 'QA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Réunion', 'RE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Romania', 'RO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Russian Federation', 'RU') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Rwanda', 'RW') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Saint Barthélemy', 'BL') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Saint Kitts and Nevis', 'KN') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Saint Lucia', 'LC') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Saint Martin (French part)', 'MF') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Saint Pierre and Miquelon', 'PM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Saint Vincent and the Grenadines', 'VC') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Samoa', 'WS') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('San Marino', 'SM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Sao Tome and Principe', 'ST') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Saudi Arabia', 'SA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Senegal', 'SN') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Serbia', 'RS') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Seychelles', 'SC') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Sierra Leone', 'SL') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Singapore', 'SG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Sint Maarten (Dutch part)', 'SX') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Slovakia', 'SK') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Slovenia', 'SI') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Solomon Islands', 'SB') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Somalia', 'SO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('South Africa', 'ZA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('South Georgia and the South Sandwich Islands', 'GS') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('South Sudan', 'SS') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Spain', 'ES') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Sri Lanka', 'LK') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Sudan', 'SD') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Suriname', 'SR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Svalbard and Jan Mayen', 'SJ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Sweden', 'SE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Switzerland', 'CH') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Syrian Arab Republic', 'SY') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Taiwan, Province of China[a]', 'TW') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Tajikistan', 'TJ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Tanzania, United Republic of', 'TZ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Thailand', 'TH') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Timor-Leste', 'TL') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Togo', 'TG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Tokelau', 'TK') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Tonga', 'TO') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Trinidad and Tobago', 'TT') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Tunisia', 'TN') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Turkey', 'TR') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Turkmenistan', 'TM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Turks and Caicos Islands', 'TC') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Tuvalu', 'TV') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Uganda', 'UG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Ukraine', 'UA') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('United Arab Emirates', 'AE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('United Kingdom of Great Britain and Northern Ireland', 'GB') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('United States of America', 'US') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('United States Minor Outlying Islands', 'UM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Uruguay', 'UY') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Uzbekistan', 'UZ') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Vanuatu', 'VU') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Venezuela (Bolivarian Republic of)', 'VE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Viet Nam', 'VN') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Virgin Islands (British)', 'VG') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Virgin Islands (U.S.)', 'VI') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Wallis and Futuna', 'WF') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Western Sahara', 'EH') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Yemen', 'YE') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Zambia', 'ZM') ON CONFLICT DO NOTHING;
INSERT INTO country(country_name, iso_code) VALUES ('Zimbabwe', 'ZW') ON CONFLICT DO NOTHING;
