version: '3.6'

services:
  neo4j:
    image: neo4j:3.5.14
    user: $NEO4J_UID:$NEO4J_GID
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-logs:/logs
      - ./neo4j-conf:/conf
    environment:
      NEO4J_ALLOW_STORE_UPGRADE: "true"
      NEO4J_AUTH: neo4j/ms-root
